### ISSUE TITLE
M365Permissions - M365Permissions.version

### ISSUE THREAD

**Issue by Cyclone47** [jflieben/assortedFunctionsV2#18]
**$PSVersionTable**

> Name                           Value
> ----                           -----
> PSVersion                      7.4.6
> PSEdition                      Core
> GitCommitId                    7.4.6
> OS                             Microsoft Windows 10.0.22631
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

**Get-InstalledModule M365Permissions | Select-Object Name, Version, PublishedDate**

> Name            Version PublishedDate
> ----            ------- -------------
> M365Permissions 1.0.9   16-12-2024 10:41:51
> PnP.PowerShell 2.12.0  9-9-2024 11:27:33

Minor issue; upon launching I get the following error

> Set-Content: C:\Users\xxxxxx\OneDrive - xxxxx x.x\Documenten\PowerShell\Modules\M365Permissions\1.0.9\private\get-AuthorizationCode.ps1:15
> Line |
>   15 |          Set-Content -Path $cachedModuleVersion -Value $global:octo.mo …
>      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Could not find a part of the path 'C:\Users\xxxxxx\AppData\Roaming\LiebenConsultancy\M365Permissions.version'.
> ![image](https://github.com/user-attachments/assets/21dea650-7058-4057-9561-9f4d0cdff510)
>

**Comment by jflieben** [comment]
Thank you for reporting @Cyclone47 ! Found the issue and will release the fix in v1.1.0

**Comment by jflieben** [comment]
should be fixed in PR https://github.com/jflieben/assortedFunctionsV2/pull/16
