### ISSUE TITLE
M365Permissions - new-GraphQuery.ps1:96

### ISSUE THREAD

**Issue by Cyclone47** [jflieben/assortedFunctionsV2#19]
**$PSVersionTable**

> Name                           Value
> ----                           -----
> PSVersion                      7.4.6
> PSEdition                      Core
> GitCommitId                    7.4.6
> OS                             Microsoft Windows 10.0.22631
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

**Get-InstalledModule M365Permissions | Select-Object Name, Version, PublishedDate**
> Name            Version PublishedDate
> ----            ------- -------------
> M365Permissions 1.0.9   16-12-2024 10:41:51
> PnP.PowerShell 2.12.0  9-9-2024 11:27:33

Issue while running the script; just after the PowerBI scan is completed I receive the following error:

> PS C:\Users\xxxxxx> Get-AllM365Permissions -expandGroups -includeCurrentUser
> Starting FULL M365 Tenant scan as xxxxxx_xxxx@xxxxxxxxxx.xx
> Planned scan order:
> 1. PowerBI permissions
> 2. Entra permissions
> 3. Exchange permissions
> 4. Onedrive permissions
> 5. Teams and Sharepoint permissions
> Starting PowerBI scan...
> Scan job cae005cb-312d-4c69-824f-52e6d8163deb completed
> Invoke-RestMethod: C:\Users\xxxxxx\OneDrive - xxxxx x.x\Documenten\PowerShell\Modules\M365Permissions\1.0.9\private\new-GraphQuery.ps1:96
> Line |
>   96 |  …    $Data = (Invoke-RestMethod -Uri $nextURL -Method $Method -Headers  …
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      |  {   "error": {     "code": "Request_ResourceNotFound",     "message": "Resource
>      | \u0027866d7ec4-3e66-4bb3-a0eb-90d33198e2e4\u0027 does not exist or one of its queried reference-property objects are
>      | not present.",     "innerError": {       "date": "2024-12-17T11:09:15",       "request-id":
>      | "fec7b20d-65c5-4cc6-a72c-c2faf165ba7c",       "client-request-id": "fec7b20d-65c5-4cc6-a72c-c2faf165ba7c"     }   } }

**Comment by Cyclone47** [comment]
The ID seems to be the tenant ID
Looks like it pulls it from the Tenant Administrators group.

`User: Tenant Administrators Type: Group GraphId: 866d7ec4-3e66-4bb3-a0eb-90d33198e2e4`

In: **get-AllPBIPermissions.ps1**

I replaced the line

> if($user.principalType -eq "Group" -and $expandGroups.IsPresent){

 with 

> if($user.principalType -eq "Group" -and $expandGroups.IsPresent -and $user.displayName -notin @("Tenant Administrators", "Whole Organization")){

**Comment by jflieben** [comment]
ah! Thanks for clarifying. I don't have that group in my own tenant, but coincidentally did encounter that group (which graph doesn't 'find') in a test tenant and fixed it in this commit: https://github.com/jflieben/assortedFunctionsV2/commit/43a1a4eef7a6285b798a304ac4dd346b90b65967

It'll be included in v1.1.0 asap.

**Comment by jflieben** [comment]
fixed in PR https://github.com/jflieben/assortedFunctionsV2/pull/16
