### ISSUE TITLE
Error running all Permissions Report

### ISSUE THREAD

**Issue by craigsummers88** [jflieben/assortedFunctionsV2#21]
I just ran the `Get-AllM365Permissions -ExpandGroups` command and got the following errors with no results:

<img width="662" alt="image" src="https://github.com/user-attachments/assets/a035a155-d654-4fff-9cc1-1366dcd9694d" />

**Comment by jflieben** [comment]
thanks for reporting @craigsummers88 !

I see 2 issues: 

1) a missing folder in AppData that the script SHOULD auto-create. I will fix that in v1.1.2. Before then, you can fix this by creating the folder manually. 
2) you're trying to scan everything, which includes PowerBI, and your user isn't licensed for PowerBI which blocks you from using the API to retrieve rights. Assign a license (temporarily) to fix this. I will also include a check for this in a future version to better warn/instruct the user.

**Comment by jflieben** [comment]
@craigsummers88 done, 1.1.2 is now in the gallery and both issues should be fixed. Code changes: https://github.com/jflieben/assortedFunctionsV2/pull/22
